# Kortare escape-time (viktigt för Vim)
set -sg escape-time 10

# Börja räkna fönster från 1 istället för 0 - enklare att nå på tangentbordet
set -g base-index 1
setw -g pane-base-index 1

# Mer historik i scrollback
set -g history-limit 10000

# Aktivera musstöd (scroll, klick på panes mm)
set -g mouse on

# 256 färger "True color"
set -g default-terminal "screen-256color"

# Enkel omladdning av config
bind r source-file ~/.tmux.conf \; display "Reloaded config!"
