# Kortare escape-time (viktigt för Vim)
set -sg escape-time 10

# Börja räkna fönster från 1 istället för 0 - enklare att nå på tangentbordet
set -g base-index 1
setw -g pane-base-index 1

# Mer historik i scrollback
set -g history-limit 10000

# Aktivera musstöd (scroll, klick på panes mm)
set -g mouse on

# 256 färger "True color"
set -g default-terminal "screen-256color"

# bindings

# vim-style navigering mellan panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Enkel omladdning av config
bind r source-file ~/.tmux.conf \; display "Reloaded config!"

# Clock mode
setw -g clock-mode-colour green

# panes
set -g pane-border-style 'fg=colour008'
set -g pane-active-border-style 'fg=colour112'

# statusbar


# "Bell" windows don't change format/style
setw -g window-status-bell-style "none"

# Refresh status line every 5 seconds
set -g status-interval 5

# status bar at the top/left
set -g status-position top
set -g status-justify left
set -g status-style 'fg=colour190'
set -g status-style 'bg=black'

set -g status-left '#S'
set -g status-left-style 'fg=colour190'
set -g status-left-length 45

set -g status-right-style 'fg=black bg=colour151'
set -g status-right ' #h %Y-%m-%d %H:%M '
set -g status-right-length 50

# Current window
setw -g window-status-current-format "\
#[fg=black, bg=colour112]\
#[fg=black, bg=colour112] #I* \
#[fg=black, bg=colour112] #W \
#[fg=colour112, bg=black]"

# Inactive windows
setw -g window-status-format "\
#[fg=black,bg=colour239]\
#[fg=colour178,bg=colour239] #I \
#[fg=colour178, bg=colour239] #W \
#[fg=colour239, bg=black]"

# messages
set -g message-style 'fg=colour196 bg=colour015 bold'

# Pane number display
set-option -g display-panes-active-colour colour112
set-option -g display-panes-colour colour008
